image: python:3.6

stages:
  - test
  - build

tests:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
    - pip install codecov
    - echo "Running unit tests…"
    - coverage run --source=. -m pytest -v -s
    - coverage report
    - codecov --token=$CODECOV_TOKEN
 # This regex will pull out the line coverage from the coverage report output so it will be displayed in the job page on Gitlab.
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  except:
    - master

deploy_package:
  stage: build
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - master
