
pruning:
  type: TaylorExpansionPrunner
  num_iterations: 9
  prune_percent: 0.1
  finetune_epochs: 3
  out_path: pruning_results


optimizer:
  type: Adam
  lr: 0.0001
  momentum: 0.9


criterion:
  type: nll


logging:
  use_tensorboard: yes
  logdir: runs
  train_log_interval: 1
