
pruning:
  num_iterations: 9
  prune_percent: 0.1
  finetune_epochs: 3
  patience: 2
  out_path: pruning_results
  early_stopping: True

optimizer:
  type: Adam
  lr: 0.0001
  momentum: 0.9

logging:
  use_tensorboard: yes
  logdir: runs
  train_log_interval: 1

  evaluate:
    eval_speed: 5 # inference iterations to average when measuring inference time, 0 for no measurement

